pipeline {
    agent any
    environment {
    APP_ENV = "${env.BRANCH_NAME == 'production' ? 'production' : 'development'}"
}

    stages {
        stage('Build') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'development') {
                        sh 'echo "Development build"'
                    } else if (env.BRANCH_NAME == 'staging') {
                        sh 'echo "Staging build"'
                    } else if (env.BRANCH_NAME == 'production') {
                        sh 'echo "Production build"'
                    }
                    sh 'mvn clean package'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying application..."'
                // Add deployment steps here
            }
        }
    }
    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
